{% set name = "plumed" %}
{% set version = "2.7.2" %}
{% set build = 2 %}
{% set mpi = mpi or "nompi" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plumed/plumed2/archive/v{{ version }}.tar.gz
  sha256: c9a31e68d6440828cf186ca43c9e11a5e5c7ad1c96b2b66ed5a5a141fc954373
# This patch is needed for plumed 2.7. It should be removed when upgrading to plumed 2.8
  patches:
    - remove-xxd-dep.patch

{% if mpi == 'nompi' %}
{% set build = build + 100 %}
{% endif %}
build:
  number: {{ build }}
  skip: true  # [win]
# Most programs should link libplumedWrapper.a so that libplumedKernel.so will be loaded
# with dlopen. There is no need for pinning thus.
# Programs linking libplumed.so should pin to min_pin='x.x', max_pin='x'.
# Programs linking libplumedKernel.so should pin to min_pin='x.x.x'. max_pin='x.x.x'.

  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  {% if mpi != "nompi" %}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - make
  host:
    - {{ mpi }}  # [mpi != "nompi"]
    - fftw
    - gsl
    - libblas
    - liblapack
    - llvm-openmp  # [osx]
    - xdrfile
    - zlib
  run:
    - {{ mpi }}  # [mpi != "nompi"]
    - gawk
    - llvm-openmp  # [osx]

test:
  commands:
    - export OMPI_MCA_plm=isolated  # [mpi == "openmpi" and linux]
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none  # [mpi == "openmpi" and linux]
    - export OMPI_MCA_rmaps_base_oversubscribe=yes  # [mpi == "openmpi" and linux]
    - plumed info --root
    - plumed info --long-version
    - plumed-patch -h
    - plumed config has external_blas external_lapack fftw gsl xdrfile zlib
    - plumed config has asmjit  # [not ppc64le and not aarch64 and not arm64]
    - plumed config has mpi  # [mpi != "nompi"]
    - $PREFIX/lib/plumed/plumed-runtime -h
    - test -f $PREFIX/lib/libplumed$SHLIB_EXT
    - test -f $PREFIX/lib/libplumedWrapper.a
    - test -f $PREFIX/lib/libplumedKernel$SHLIB_EXT

about:
  home: http://www.plumed.org/
  license: LGPL-3.0-only
  license_family: GPL
  license_file: COPYING.LESSER
  summary: Free energy calculations in molecular systems
  description: |
    PLUMED is an open source library for free energy calculations in
    molecular systems which works together with some of the most
    popular molecular dynamics engines.
  doc_url: https://www.plumed.org/doc
  dev_url: https://github.com/plumed/plumed2

extra:
  recipe-maintainers:
    - GiovanniBussi
